# Generated by Django 5.0.4 on 2024-04-21 08:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuisineType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Meet',
            fields=[
                ('id', models.AutoField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('foodimg', models.TextField()),
                ('title', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('website', models.TextField()),
                ('meetdatetime', models.DateTimeField()),
                ('abuseflag', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('CuisineType', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='foodjio_api.cuisinetype')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MeetParticipants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('meet', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='foodjio_api.meet')),
            ],
            options={
                'unique_together': {('meet', 'account')},
            },
        ),
    ]
