# Generated by Django 5.0.4 on 2024-04-23 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodjio_api', '0002_meet_maxnum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meet',
            name='full',
        ),
        migrations.AddField(
            model_name='meet',
            name='Is_full',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
