# Generated by Django 5.0.4 on 2024-04-23 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodjio_api', '0003_remove_meet_full_meet_is_full'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meet',
            old_name='Is_full',
            new_name='is_full',
        ),
    ]
