# Generated by Django 5.0.4 on 2024-04-19 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodjio_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='img',
            field=models.TextField(default=''),
        ),
    ]
